# Generated by Django 3.2.17 on 2023-02-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_auto_20230209_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
