# Generated by Django 3.2.17 on 2023-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=250),
        ),
    ]
